### ISSUE TITLE
关于redis默认安装没有设置密码的情况启动是不是报错？

### ISSUE THREAD

**Issue by diaodiaofly** [mauersu/redis-admin#10]
你好，如题
我的redis默认没有密码，我将你的配置修改为如下：
redis.server.num=1
redis.language=English

#must set a default-name redis
redis.host.1=127.0.0.1
redis.name.1=127.0.0.1
redis.port.1=6379
redis.password.1=

#redis.host.2=127.0.0.1
#redis.name.2=127.0.0.1
#redis.port.2=6380
#redis.password.2=root

启动报错
严重: Context [] startup failed due to previous errors
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 59 more
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: ERR invalid DB index; nested exception is redis.clients.jedis.exceptions.JedisDataException: ERR invalid DB index
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:44)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:36)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
	at org.springframework.data.redis.connection.jedis.JedisConnection.select(JedisConnection.java:931)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:151)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:144)
	at com.mauersu.util.RedisApplication.createRedisConnection(RedisApplication.java:137)
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:46)
	... 66 more
Caused by: redis.clients.jedis.exceptions.JedisDataException: ERR invalid DB index
	at redis.clients.jedis.Protocol.processError(Protocol.java:115)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:182)
	at redis.clients.jedis.BinaryJedis.select(BinaryJedis.java:409)
	at org.springframework.data.redis.connection.jedis.JedisConnection.select(JedisConnection.java:929)
	... 70 more

**Comment by diaodiaofly** [comment]
reidis 设置密码的情况是可以正常使用
没有密码  去掉配置的密码连接不上

**Comment by admindxh** [comment]
我也有这个问题

**Comment by mauersu** [comment]
@diaodiaofly @admindxh 我测试了下连接windows下的redis没有密码情况，没有出现你俩说的问题，我没有密码也可以连接
