### ISSUE TITLE
连接阿里云服务器报异常

### ISSUE THREAD

**Issue by ikaren** [mauersu/redis-admin#9]
本地测试OK，放到阿里云服务器上，连接阿里云redis报异常：
Caused by: java.lang.IllegalArgumentException: unknown data type code

**Comment by ikaren** [comment]
后来又变成这个异常：
Caused by: java.net.SocketException: Socket closed

**Comment by mauersu** [comment]
@ikaren 可否提供下服务器信息或者把异常截个完整的图吧

**Comment by ikaren** [comment]
@mauersu ，OK，异常信息发你163邮箱了。

**Comment by mauersu** [comment]
发一下 redis.properties 文件信息，密码可以省略

**Comment by ikaren** [comment]
redis.server.num=1
redis.language=English

#must set a default-name redis
redis.host.1=xxx
redis.name.1=redis
redis.port.1=6379
redis.password.1=xxx

试过redis.host可以访问，只是在redis-admin连接不上。

**Comment by mauersu** [comment]
@ikaren　com.mauersu.util.InitContext.initRedisServers(InitContext.java:55)　这里的代码报错，初始化链接时候，信息太少，帮不上忙了

**Comment by ikaren** [comment]
@mauersu ，所有异常信息都发你邮箱了啊，那再贴一遍吧，
异常情况1：
22-Jun-2016 15:03:50.833 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[22/06/16 03:04:23:023 CST] localhost-startStop-1 ERROR util.InitContext: initRedisServers: XXX-redis-server occur Throwable :java.net.SocketException: Socket closed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
[22/06/16 03:04:23:023 CST] localhost-startStop-1  WARN support.AnnotationConfigWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initContext': Invocation of init method failed; nested exception is com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 27 more
Caused by: org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Socket closed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:47)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:36)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1055)
	at com.mauersu.util.ConvertUtil.convertByteToString(ConvertUtil.java:21)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:153)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:142)
	at com.mauersu.util.RedisApplication.createRedisConnection(RedisApplication.java:135)
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:46)
	... 34 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:210)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:47)
	at redis.clients.jedis.Protocol.process(Protocol.java:131)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:182)
	at redis.clients.jedis.BinaryJedis.type(BinaryJedis.java:201)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1053)
	... 39 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:190)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:108)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:204)
	... 46 more
[22/06/16 03:04:23:023 CST] localhost-startStop-1 ERROR context.ContextLoader: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initContext': Invocation of init method failed; nested exception is com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 27 more
Caused by: org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Socket closed; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:47)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:36)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1055)
	at com.mauersu.util.ConvertUtil.convertByteToString(ConvertUtil.java:21)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:153)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:142)
	at com.mauersu.util.RedisApplication.createRedisConnection(RedisApplication.java:135)
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:46)
	... 34 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Socket closed
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:210)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:47)
	at redis.clients.jedis.Protocol.process(Protocol.java:131)
	at redis.clients.jedis.Protocol.read(Protocol.java:196)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:283)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:182)
	at redis.clients.jedis.BinaryJedis.type(BinaryJedis.java:201)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1053)
	... 39 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:190)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.net.SocketInputStream.read(SocketInputStream.java:108)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:204)
	... 46 more
22-Jun-2016 15:04:23.797 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
22-Jun-2016 15:04:23.805 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/redis-admin] startup failed due to previous errors
22-Jun-2016 15:04:23.813 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [redis-admin] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
22-Jun-2016 15:04:23.817 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR

**Comment by ikaren** [comment]
异常情况2：
23-Jun-2016 11:33:09.304 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[23/06/16 11:33:42:042 CST] localhost-startStop-1 ERROR util.InitContext: initRedisServers: XXX-redis-server occur Throwable :Unknown redis exception; nested exception is java.lang.IllegalArgumentException: unknown data type code
[23/06/16 11:33:42:042 CST] localhost-startStop-1  WARN support.AnnotationConfigWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initContext': Invocation of init method failed; nested exception is com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 27 more
Caused by: org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.IllegalArgumentException: unknown data type code
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:48)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:38)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1055)
	at com.mauersu.util.ConvertUtil.convertByteToString(ConvertUtil.java:21)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:153)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:142)
	at com.mauersu.util.RedisApplication.createRedisConnection(RedisApplication.java:135)
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:46)
	... 34 more
Caused by: java.lang.IllegalArgumentException: unknown data type code
	at org.springframework.data.redis.connection.DataType.fromCode(DataType.java:64)
	at org.springframework.data.redis.connection.convert.StringToDataTypeConverter.convert(StringToDataTypeConverter.java:32)
	at org.springframework.data.redis.connection.convert.StringToDataTypeConverter.convert(StringToDataTypeConverter.java:26)
	at org.springframework.data.redis.connection.convert.Converters.toDataType(Converters.java:69)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1053)
	... 39 more
[23/06/16 11:33:42:042 CST] localhost-startStop-1 ERROR context.ContextLoader: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initContext': Invocation of init method failed; nested exception is com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mauersu.exception.RedisInitException: XXX-redis-server init failed
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
	... 27 more
Caused by: org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.IllegalArgumentException: unknown data type code
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:48)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:38)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:195)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1055)
	at com.mauersu.util.ConvertUtil.convertByteToString(ConvertUtil.java:21)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:153)
	at com.mauersu.util.RedisApplication.initRedisKeysCache(RedisApplication.java:142)
	at com.mauersu.util.RedisApplication.createRedisConnection(RedisApplication.java:135)
	at com.mauersu.util.InitContext.initRedisServers(InitContext.java:46)
	... 34 more
Caused by: java.lang.IllegalArgumentException: unknown data type code
	at org.springframework.data.redis.connection.DataType.fromCode(DataType.java:64)
	at org.springframework.data.redis.connection.convert.StringToDataTypeConverter.convert(StringToDataTypeConverter.java:32)
	at org.springframework.data.redis.connection.convert.StringToDataTypeConverter.convert(StringToDataTypeConverter.java:26)
	at org.springframework.data.redis.connection.convert.Converters.toDataType(Converters.java:69)
	at org.springframework.data.redis.connection.jedis.JedisConnection.type(JedisConnection.java:1053)
	... 39 more
23-Jun-2016 11:33:42.168 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
23-Jun-2016 11:33:42.177 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/redis-admin] startup failed due to previous errors
23-Jun-2016 11:33:42.186 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [redis-admin] appears to have started a thread named [commons-pool-EvictionTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
23-Jun-2016 11:33:42.190 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR

**Comment by mauersu** [comment]
@ikaren  这个需要远程debug 定位 错误到底在哪的

**Comment by mauersu** [comment]
可以的话，把服务器密码更改下，我登上去定位下问题

**Comment by mauersu** [comment]
@ikaren 或者 本地连接远程redis，本地debug定位，可以的话告诉我下 redis用户名 密码

**Comment by ikaren** [comment]
@mauersu ，这个redis服务器是公司的，不方便告诉你用户名密码，见谅。
试过放在我自己的阿里redis服务器，连接是OK的，猜测应该是公司的服务器哪里限制了。现在找到了替代品rinetd来用。
感谢你的帮助。

**Comment by mauersu** [comment]
额，可以用telnet测试下redis端口，看看咋回事
